---
- hosts: localhost
  become: true
  become_user: root
  roles:
    - {role: common, tags: common}
    - {role: docker, tags: docker}
    - {role: nginx-native, tags: nginx-native}
    - {role: prometheus, tags: prometheus}
    - {role: elasticsearch-swarm, tags: elasticsearch}
    - {role: nginx-swarm, tags: nginx-swarm}
    - {role: data-scraper, tags: data-scraper}
