---
# Install

- name: Create daemontools working directory
  file:
    path: "{{ daemontools_bin_directory }}"
    state: directory
    mode: 1755

- name: Download and unarchive
  ansible.builtin.unarchive:
    src: "{{ daemontools_bin_url }}"
    dest: "{{ daemontools_bin_directory }}"
    remote_src: yes

