---
# Install
- name: Install required packages
  apt:
    name: "{{ daemontools_installed_packages }}"
    state: latest

- name: Create daemontools working directory
  file:
    path: "{{ daemontools_bin_directory }}"
    state: directory
    mode: 1755

- name: Add svscan to startup
  copy:
    src: 'rc.local'
    dest: '/etc/rc.local'
    mode: a+x

- name: Check if its svscan running
  shell: 'ps axuf | grep s[v]scanboot'
  failed_when: false
  register: svscan_status

- name: show output
  debug:
    var: svscan_status

      # name: Not running yet, starting up
      # svstat  /etc/service/save-current-time

- name: Create data scraper dir
  file:
    path: "{{ daemontools_bin_directory }}/data-scraper"
    state: directory
    mode: 0750

- name: Add data-scraper service
  copy:
    src: 'data-scraper.sh'
    dest: "{{ daemontools_bin_directory }}/data-scraper/run"
    mode: +x
