---
# Install
- name: Install required packages
  apt:
    name: "{{ daemontools_installed_packages }}"
    state: latest

- name: Create daemontools working directory
  file:
    path: "{{ daemontools_bin_directory }}"
    state: directory
    mode: 1755

- name: Add svscan to startup
  copy:
    src: 'rc.local'
    dest: '/etc/rc.local'
    mode: a+x

- name: Check if its svscan running
  command: 'ps | grep "s[v]scan"'
  register: svscan_status

- name: show output
  debug:
    var: svscan_status
