---
# Install
- name: Install required packages
  apt:
    name: "{{ daemontools_installed_packages }}"
    state: latest

- name: Create daemontools working directory
  file:
    path: "{{ daemontools_bin_directory }}"
    state: directory
    mode: 1755
