---
# defaults 
ansible_python_interpreter: /usr/bin/python3

admin_mail: "smowky@psylogical.org"

# nginx
nginx_conf_directory: '/etc/nginx'
nginx_vhost_directory: "{{ nginx_conf_directory }}/sites-enabled"
nginx_ssl_directory: '/etc/ssl'
  
# certbot
certbot_image: certbot/certbot
certbot_hostname: cb01
certbot_conf_dir: '/tmp'
certbot_email: "{{ admin_mail }}"
