---
# install
nginx_native_installed_packages:
  - python3-requests
  - ssl-cert
  - nginx

nginx_conf_directory: '/etc/nginx'
nginx_root_directory: '/var/www/html'
nginx_ssl_directory: '/etc/ssl'
nginx_configuration_directory: "{{ nginx_conf_directory }}/conf.d"

nginx_worker_connections: 4096

# ssl config
nginx_ssl_protocols: "TLSv1.2 TLSv1.3"
nginx_ssl_ciphers: 'ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-CHACHA20-POLY1305'
  
  
nginx_access_logs: '/var/log/nginx/access.log' 
nginx_error_logs: '/var/log/nginx/error.log'

# custom settings
nginx_disable_default_ssl: true
nginx_default_server_name: 'cdn.psylogical.org'
