---
- name: Create stack directory
  file:
    path: "{{ swarm_prometheus_stack_dir }}"
    state: directory

- name: Copy prometheus stack prescription
  template:
    src: "prometheus_stack.yml.j2"
    dest: "{{ swarm_prometheus_stack_dir }}/prometheus_stack.yml"
    lstrip_blocks: yes
    mode: '600'

- name: Create prometheus config directory
  file:
    path: "{{ swarm_prometheus_config_dir }}"
    state: directory

- name: Copy prometheus config prescription
  template:
    src: "prometheus_config.yml.j2"
    dest: "{{ swarm_prometheus_config_dir }}/prometheus.yml"
    lstrip_blocks: yes
    mode: '600'

- name: Ensure there is prometheus
  docker_stack:
    state: present
    name: prometheus
    compose:
      - "{{ swarm_prometheus_stack_dir }}/prometheus_stack.yml"
  tags: stack-reload

- name: Enable nginx grafana vhost on hypervisor
  template:
    src: 'grafana_vhost.conf.j2'
    dest: "{{ nginx_vhost_directory }}/grafana.conf"
  notify:
    - Reload native nginx

- name: Check if certificate already exist
  stat:
    path: "{{ nginx_ssl_directory }}/live/{{ grafana_server_name }}/cert.pem"
  register: grafana_certificate

- name: Issue a certificate
  block:
    - name: Issue a certificate
      include_tasks: create-certificate.yml
  when:
    - grafana_ssl
    - grafana_certificate.stat.exists == false

- name: Flush handlers # fix failure in first deploy, due missing grafana vhost on nginx unable to communicate with grafana
  meta: flush_handlers

- name: Update /etc/hosts with grafana record # just to make sure if dns record is not set
  lineinfile:
    path: '/etc/hosts'
    line: '127.0.1.2 grafana-cdn.psylogical.org'

- name: Install grafana dashboards
  block:
    - name: grafana dashoards
      include_tasks: dashboards-grafana.yml
  tags:
    - dashboards-grafana

      # TODO alerting      
