---

- name: Reload prometheus
  shell: "docker service update --force prometheus_promethes"
  register: result
  until: result.stdout.find("Service converged") != -1
  retries: 5
  delay: 60

- name: Reload nginx
  systemd:
    name: nginx
    state: reloaded
