---
# defaults
nginx_swarm_conf_directory: '/opt/nginx'
nginx_swarm_root_directory: '/opt/www/html'
nginx_swarm_ssl_directory: '/opt/ssl'
nginx_swarm_configuration_directory: "{{ nginx_swarm_conf_directory }}/conf.d"
nginx_swarm_vhost_directory: "{{ nginx_swarm_conf_directory }}/sites-enabled" 
nginx_swarm_log_directory: "{{ nginx_swarm_conf_directory }}/logs" 

nginx_swarm_worker_connections: 4096

# ssl config
nginx_swarm_ssl: false
nginx_swarm_ssl_protocols: "TLSv1.2 TLSv1.3"
nginx_swarm_ssl_ciphers: 'ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-CHACHA20-POLY1305'
  
# logging
nginx_swarm_access_logs: "{{ nginx_swarm_log_directory }}/access.log"
nginx_swarm_error_logs: "{{ nginx_swarm_log_directory }}/error.log"

# custom settings
nginx_swarm_extra_volumes: []
nginx_swarm_default_server_name: 'swarm-cdn.psylogical.org'

# certificate
certbot_image: certbot/certbot
certbot_hostname: cb01
certbot_conf_dir: /etc/ssl/custom
certbot_email: "{{ admin_mail }}"

# swarm
nginx_swarm: false
nginx_swarm_stack_dir: '/root/nginx'
nginx_swarm_config_dir: '{{ nginx_swarm_stack_dir }}/nginx'
nginx_swarm_docker_image: nginx
nginx_swarm_docker_image_version: latest
nginx_swarm_ssl_certs_dir: '/etc/ssl/custom'
nginx_swarm_ssl_snake_oil_cert: '/etc/ssl/certs/ssl-cert-snakeoil.pem'
nginx_swarm_ssl_snake_oil_key: '/etc/ssl/private/ssl-cert-snakeoil.key'
